In [0]:
import pandas as pd
import numpy as np

#Load the data.
df = pd.read_csv('comments_with_scores.csv')

In [37]:
df.head()

                                                text  by  ...    pos    neu
0  I lived in China for 3 years and speak pretty ...  b6  ...  0.166  0.740
1  Have you lived in China? Your suggestion, if t...  b6  ...  0.000  0.759
2  I can tell you some thoughts I have, but pleas...  b6  ...  0.098  0.845
3  I find myself a little irritated by the termin...  b6  ...  0.103  0.825
4  > Criticizing their area of focus helps no one...  b6  ...  0.119  0.684

[5 rows x 11 columns]

In [26]:
df.tail()

                                                   text  ...    neu
9769  I can't get onboard with this interpretation. ...  ...  0.881
9770  And your secret 12 words, even if never reveal...  ...  1.000
9771  eh, not really. It's true that Canvas is its o...  ...  0.873
9772  By this logic though, aren't all abstractions ...  ...  0.781
9773                           what's the side project?  ...  1.000

[5 rows x 11 columns]

In [38]:
# Look for a user with the most negative (salty) score.
df.sort_values(['neg'], ascending=False)

                                                   text  ...    neu
3761                                 Poor poor redskins  ...  0.139
9702                                          holy shit  ...  0.217
2271  Because death is really serious business. Misi...  ...  0.264
5420  http://www.letters4words.com/jaxy.htmi.e. ass,...  ...  0.300
3687                        Why are gun companies evil?  ...  0.306
...                                                 ...  ...    ...
6195  >"we're better than you, we're smarter than yo...  ...  0.832
2153  I wonder how often less high profile folks get...  ...  0.857
2154  I always found Germans pretty accommodating ab...  ...  0.842
2156  No.[1][1] https://en.wikipedia.org/wiki/Better...  ...  1.000
9773                           what's the side project?  ...  1.000

[9774 rows x 11 columns]

In [39]:
df_user = df.loc[df['by'] == 'socceroos']
df_user.head()

                                                   text  ...    neu
6674  You're right, the implications are huge.Unless...  ...  0.754
6675  Yeah, ASD haven't got the best relationship wi...  ...  0.722
6676  Do you mean that the approach of DDD feels obs...  ...  0.743
6677  Presumably because he spent that time engaged ...  ...  0.709
6678  Exactly, when the automation need arises just ...  ...  1.000

[5 rows x 11 columns]

In [40]:
df_neg = df_user.sort_values(['neg'], ascending=False)
df_neg.head(20)

                                                   text  ...    neu
6697      Poorly disguised communism. I'm disappointed.  ...  0.366
6685  ...excluding the dead victim. Because, you kno...  ...  0.479
6744         ...I sense an oncoming existential crisis.  ...  0.549
6693  I was legitimately disappointed realising this...  ...  0.485
6696  Spacebar/pgdwn is a harsh context break for me...  ...  0.660
6753                     That's not true though, is it.  ...  0.682
6768          hhhhh, keys in RAM. Life is so difficult.  ...  0.684
6754  Americans are more aggressive in strategy - wh...  ...  0.610
6710  5D optical data storage is all the rage these ...  ...  0.728
6709  Logical fallacy. You've built a strawman, base...  ...  0.730
6686  I can't stand the UK any more. I used to be pa...  ...  0.760
6770  Rant incoming - this isn't targeted at you, bu...  ...  0.751
6718  Wilson didn't die. Wilson left him. I assume t...  ...  0.709
6743  I'd prefer to describe it as slashing a dead h...  ...  0.774
6748  > If I do not control what happens to my body,...  ...  0.721
6728  My thoughts exactly. Poor fella.I've seen wors...  ...  0.755
6684  It will always come back to threatening human ...  ...  0.819
6751  The more technology integrates with us the les...  ...  0.654
6726  I guess if your side project betrays a distinc...  ...  0.803
6699  Yeah, I can see how one could make an amoral, ...  ...  0.733

[20 rows x 11 columns]

In [41]:
# View the comments in plain text for easier reading.
for text in df_user.sort_values(by='neg', ascending=False)['text'].head(20):
    print(text, '\n')

Poorly disguised communism. I'm disappointed.

...excluding the dead victim. Because, you know, he's lost his rights.

...I sense an oncoming existential crisis.

I was legitimately disappointed realising this was an April Fools joke.

Spacebar/pgdwn is a harsh context break for me. There's no continuity like a book or touch screen

That's not true though, is it.

hhhhh, keys in RAM. Life is so difficult.

Americans are more aggressive in strategy - which includes outsourcing. It also makes them more prone to being aggressively stupid and aggressively short-sighted.But hey, profits.

5D optical data storage is all the rage these days. Wouldn't want your data to disappear with a tectonic plate shift.

Logical fallacy. You've built a strawman, based your argument off it, and then contradicted yourself.

I can't stand the UK any more. I used to be patriotic, but now I hate the place. It's one giant police state. That the people living there can't see this sickens me.

Rant incoming - this isn't targeted at you, but my observations on this.I've always found it ridiculous that effectively 1 planck-time can be the difference between a collection of cells and a human and therefore the difference between selfish rights and outraged sorrow.The idea that you can draw the line arbitrarily along a child's development other than the very moment of inception and call one a self-centered right and the other murder is preposterous.The very fact that it is the premeditated interference that prevents the baby from continuing to develop should be the light-bulb moment for most discerning and logical individuals. You literally have to kill the baby to stop it from becoming a fully-formed version of itself - that is literally it. You have to kill it to stop it from getting to a point that you 'begin to feel bad'. It is ridiculous.The fact that, when unimpeded, that baby will grow into an adult individual should be a pretty obvious reminder to people of what they're actually doing.I've been saying this for a little while, but I'm sure a time will come when society collectively looks back on this period and shudders at the horror of it all.

Wilson didn't die. Wilson left him. I assume that Wilson dying would require severe degeneration or destruction such as a shark ripping the ball in pieces.

I'd prefer to describe it as slashing a dead horse's rotten corpse with a katana. As the bloat and flesh of the ecosystem has disintegrated we're able to observe the framework more clearly - the bone structure of the horse, if you will. Using the katana we are making precise, incisive blows to the remnants as we extract meaning from it's corpse - or lessons learned, if you will....perhaps I'm taking the analogy too far?

> If I do not control what happens to my body, what freedom do I have?This argument is again one that rejects the moral responsibility to the human child growing in the body. The notion that discontent with the situation justifies killing a human doesn't stack up.The point about the broken USA healthcare system will never justify the killing of unborn children. It also serves as a first-world excuse that is essentially based around inconvenience.Finally, the argument that "others do horrible things so therefore why can't we do this horrible thing too" doesn't make any kind of sense either.

My thoughts exactly. Poor fella.I've seen worse though. A newish officer spilled his morning coffee into the circuitry of a device worth over 10 zeros. Immediately short circuited.

It will always come back to threatening human lives. You can always smash machines against each other, but ultimately it's pointless until the humans themselves are threatened with their lives.

The more technology integrates with us the less freedom we have and the stupider we become.

I guess if your side project betrays a distinct lack of knowledge of basic programming then it could hurt you.My suggestion would be to use your project as a springboard during any potential interviews to detail the areas in which you have grown as a programmer since the project's creation.

Yeah, I can see how one could make an amoral, pedantic argument around the definition of working from home. But to do that you have to 1) remove the argument from it's surrounding context, which is flawed reasoning and 2) successfully prove that there is a significant difference in the practical outworking of the definition of working from home between the subject and their workmates. The latter is immediately and significantly relevant to the definition and, unfortunately for the oppressor, drags context back into play.